CREATE SEQUENCE SEQ_Usuario START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_Anuncio START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_Reserva START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_Foto START WITH 1 INCREMENT BY 1;

/* Opcional
CREATE SEQUENCE SEQ_Cidade START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_Estado START WITH 1 INCREMENT BY 1;
*/